import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../extension/", import.meta.url);

test("extension is a narrowly scoped Manifest V3 ESPN companion", async () => {
  const manifest = JSON.parse(await readFile(new URL("manifest.json", root), "utf8"));
  assert.equal(manifest.manifest_version, 3);
  assert.ok(manifest.host_permissions.every((host) => /espn\.com/.test(host)));
  assert.ok(manifest.content_scripts.some((script) => script.matches.includes("https://fantasy.espn.com/*")));
});

test("draft actions fail closed and private ESPN credentials are not persisted", async () => {
  const [background, content, bridge, page] = await Promise.all([
    readFile(new URL("background.js", root), "utf8"),
    readFile(new URL("espn-content.js", root), "utf8"),
    readFile(new URL("app-bridge.js", root), "utf8"),
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
  ]);
  assert.doesNotMatch(background, /chrome\.storage|espn_s2|SWID/);
  assert.match(background, /findEspnContext\(expectedLeagueId, expectedTabId\)/);
  assert.match(background, /findEspnContext\(message\.payload\?\.expectedLeagueId, expectedTabId\)/);
  assert.match(background, /DRAFT_TAB_REQUIRED/);
  assert.match(background, /DRAFT_TAB_CHANGED/);
  assert.match(background, /REFRESH_ESPN_CONTEXT/);
  assert.match(background, /chrome\.tabs\.get\(expectedTabId\)/);
  assert.match(background, /findUniqueDraftRoomContext/);
  assert.match(background, /matches\.length === 1/);
  assert.match(background, /RELOAD_EXTENSION/);
  assert.match(background, /\["localhost", "127\.0\.0\.1"\]/);
  assert.match(background, /chrome\.runtime\.reload\(\)/);
  assert.match(background, /receptionPoints === 0 \? "Standard"/);
  assert.doesNotMatch(background, /pollDraft\(\{ \.\.\.message\.payload, season: 2026 \}\)/);
  assert.match(content, /NOT_ON_CLOCK/);
  assert.match(content, /PICK_CHANGED/);
  assert.match(content, /CLOCK_TOO_SHORT/);
  assert.match(content, /MIN_ACTION_WINDOW_SECONDS = 5/);
  assert.match(content, /hasSafeActionWindow/);
  assert.match(content, /nominationSelectionActive/);
  assert.match(content, /auction-pick-component--selecting/);
  assert.match(content, /selectingAuctionPick === ownAuctionPick/);
  assert.match(content, /\^select\$/);
  assert.match(content, /!currentBidMatch/);
  assert.match(content, /waitingTeamMatch/);
  assert.match(content, /\.on-the-clock/);
  assert.match(content, /closest\?\.\("\.current-pick-module-container"\)/);
  assert.match(content, /\.pick-component\.own-pick \.team-name/);
  assert.match(content, /normalizePlayerName\(snakeClockTeam\) === normalizePlayerName\(ownDraftTeam\)/);
  assert.match(content, /availablePlayerIds/);
  assert.match(content, /players\/full/);
  assert.match(content, /WRONG_LEAGUE/);
  assert.match(content, /NOMINEE_MISMATCH/);
  assert.match(content, /NOMINEE_UNKNOWN/);
  assert.match(content, /BID_CHANGED/);
  assert.match(content, /BID_OUT_OF_SEQUENCE/);
  assert.match(content, /BUDGET_UNKNOWN/);
  assert.match(content, /BUDGET_RESERVE/);
  assert.match(content, /maxLegalBid/);
  assert.match(content, /\.budgets-table \[role='row'\]/);
  assert.match(content, /auction-pick-component--own \.team-name/);
  assert.match(content, /ACTION_NOT_FOUND/);
  assert.match(content, /nominationHasStarted/);
  assert.match(content, /NOMINATION_STARTED/);
  assert.match(content, /#icon__controls__volume_mute/);
  assert.match(content, /activeVolumeIcon === "#icon__controls__volume_mute"/);
  assert.match(content, /actionSurfaceReady/);
  assert.match(content, /auctionBudgets/);
  assert.match(content, /updateAuctionSales/);
  assert.match(content, /auctionSales/);
  assert.match(content, /INVALID_OPENING_BID/);
  assert.match(content, /requireOnClock/);
  assert.match(content, /\[data-testid='player-selected'\]/);
  assert.match(content, /current \(\?:bid\|offer\)/);
  assert.match(content, /\[role='grid'\] \[role='row'\]/);
  assert.match(content, /visiblePlayerSearchInput/);
  assert.match(content, /MAX_SEARCH_CANDIDATES = 7/);
  assert.match(content, /PLAYER_RESOLUTION_WINDOW_MS = 4000/);
  assert.match(content, /candidates\.slice\(0, MAX_SEARCH_CANDIDATES\)/);
  assert.match(content, /\^offer/);
  assert.match(content, /exactIncrementalBidControl/);
  assert.match(content, /maxApprovedBid/);
  assert.match(content, /bidRetryCount/);
  assert.match(content, /SELECT_CONFIRMATION_WINDOW_MS = 1200/);
  assert.match(content, /MAX_SELECT_RETRIES = 2/);
  assert.match(content, /function rosterHasPlayer\(context, playerId, playerName\)/);
  assert.match(content, /function playerNamesMatch\(left, right\)/);
  assert.match(content, /code: "ROSTER_CONFIRMED"/);
  assert.match(content, /code: "ROSTER_NOT_CONFIRMED"/);
  assert.match(content, /selectRetryCount/);
  assert.match(content, /WALK_AWAY/);
  assert.match(content, /action\.operation === "BID" \? 180 : 1500/);
  assert.match(content, /\(\?:offer\|bid\)/);
  assert.match(content, /action\.operation !== "BID"/);
  assert.match(content, /function sendToCompanion\(message\)/);
  assert.match(content, /chrome\.runtime\?\.id/);
  assert.match(bridge, /function announceReady\(\)/);
  assert.match(bridge, /event\.data\.type === "APP_HELLO"/);
  assert.match(page, /sendToExtension\("APP_HELLO"\)/);
  assert.match(page, /type === "COMMAND_RESULT" && payload\?\.ready/);
  assert.match(page, /current === "connected" \? current : "ready"/);
  assert.match(page, /expectedCurrentBid: resolvedOperation === "BID"/);
  assert.match(page, /maxApprovedBid: resolvedOperation === "BID"/);
  assert.match(page, /payload\.action\?\.operation === "BID"/);
  assert.match(page, /actionRequestId/);
  assert.match(page, /actionRequestId !== latestActionRequestRef\.current/);
  assert.match(page, /latestActionRequestRef\.current = \+\+actionRequestSequenceRef\.current/);
  assert.match(page, /ESPN confirmed \$\{pendingAuctionBid\.playerName\} on your roster/);
  assert.match(page, /automaticRecommendations = player\.fillsMandatoryStarter/);
  assert.match(page, /espnNameMatchesPlayer/);
  assert.match(page, /slots\.filter\(\(slot\) => slot !== "BN"\)/);
  assert.match(page, /Math\.max\(1, Number\(context\.currentBid \|\| 0\) \+ 1\)/);
  assert.match(page, /contextMatchesActiveDraftTab/);
  assert.match(page, /expectedTabId/);
  assert.match(page, /REFRESH_ESPN_CONTEXT/);
  assert.match(page, /setInterval\(refreshExactDraftTab, 750\)/);
  assert.match(page, /contextCanRebindDraftTab/);
  assert.match(page, /reloadCompanion/);
  assert.doesNotMatch(page, /profileForEspnRoom/);
  assert.match(page, /liveRecommendations/);
  assert.match(page, /actionWindowOpen/);
  assert.match(page, /bidWindowOpen/);
  assert.match(page, /beforeRosterPlayerIds/);
  assert.match(page, /newOwnRoster\.length === 1/);
  assert.match(page, /ESPN_ROSTER_CONFIRMATION_GRACE_MS = 6000/);
  assert.match(page, /INTELLIGENCE_REFRESH_MS = 5 \* 60 \* 1000/);
  assert.match(page, /cache: "no-store"/);
  assert.match(page, /setInterval\(refreshIntelligence, INTELLIGENCE_REFRESH_MS\)/);
  assert.match(page, /preflightChecks/);
  assert.match(page, /liveChecks/);
  assert.match(page, /liveChecklistReady/);
  assert.match(page, /pendingAuctionNominationRef/);
  assert.match(page, /ownNominationIntent === "DRAIN"/);
  assert.match(page, /resolveAuctionSales/);
});
